modLoader="javafml"
loaderVersion="[32,)"
license="GNU General Public License V3"
issueTrackerURL="https://github.com/PugsMods/RandomDeathMessage/issues"
[[mods]]
modId="randomdeathmessage"
version="1.0.4"
displayName="RandomDeathMessage"
updateJSONURL="https://raw.githubusercontent.com/PugsMods/RandomDeathMessage/master/src/main/java/com/putopug/randomdeathmessage/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/randomdeathmessage"
logoFile="RDM.png"
credits="My Pc - Letting me Mod"
authors="PugzAreCure"
description='''Random death messages!'''
[[dependencies.randomdeathmessage]]
    modId="forge"
    mandatory=true
    versionRange="[32,37)"
    ordering="NONE"
    side="BOTH"
[[dependencies.randomdeathmessage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
