modLoader="javafml"
loaderVersion="[32,)"
license="GNU Lesser General Public License V3"
issueTrackerURL="https://github.com/PugsMods/RandomDeathMessage/issues"
[[mods]]
modId="randomdeathmessage"
version="1.3.1"
displayName="RandomDeathMessage"
updateJSONURL="https://raw.githubusercontent.com/PugsMods/RandomDeathMessage/master/src/main/java/com/putopug/randomdeathmessage/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/randomdeathmessage"
logoFile="RDM.png"
#credits=""
authors="PugzAreCure"
description='''Random death messages!'''
[[dependencies.randomdeathmessage]]
    modId="forge"
    mandatory=true
    versionRange="[40,41)"
    ordering="NONE"
    side="BOTH"
[[dependencies.randomdeathmessage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
